[package]
name = "jilar"
version = "0.1.0"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[dependencies]
cairo-rs = "0.9.0"
pango = "0.9.0"
pangocairo = "0.10.0"
cascade = "0.1.4"

pugl-ui = "0.2.0"
pugl-sys = "0.3.3"
